export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const FETCH_PRODUCT_LIST_SUCCESS = 'FETCH_PRODUCT_LIST_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const TOGGLE_OPEN_CART = 'TOGGLE_OPEN_CART';
